// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmegaAgenda.Data;

namespace OmegaAgenda.Migrations
{
    [DbContext(typeof(OmegaAgendaContext))]
    [Migration("20210502222254_SchedulingAdjusts")]
    partial class SchedulingAdjusts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OmegaAgenda.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("OmegaAgenda.Models.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Professional");
                });

            modelBuilder.Entity("OmegaAgenda.Models.Scheduling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CustomerNameId");

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("EndTime");

                    b.Property<int?>("ProfessionalId");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNameId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("Scheduling");
                });

            modelBuilder.Entity("OmegaAgenda.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("SchedulingId");

                    b.Property<string>("ServiceDescription");

                    b.Property<string>("ServiceName");

                    b.HasKey("Id");

                    b.HasIndex("SchedulingId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("OmegaAgenda.Models.Scheduling", b =>
                {
                    b.HasOne("OmegaAgenda.Models.Customer", "CustomerName")
                        .WithMany("Schedules")
                        .HasForeignKey("CustomerNameId");

                    b.HasOne("OmegaAgenda.Models.Professional", "Professional")
                        .WithMany("Schedules")
                        .HasForeignKey("ProfessionalId");
                });

            modelBuilder.Entity("OmegaAgenda.Models.Service", b =>
                {
                    b.HasOne("OmegaAgenda.Models.Scheduling")
                        .WithMany("Services")
                        .HasForeignKey("SchedulingId");
                });
#pragma warning restore 612, 618
        }
    }
}
